### ISSUE TITLE
Sensitive Data Disclosure - zuliprc

### ISSUE THREAD

**Issue by chandansgowda** [zulip/zulip-terminal#1313]
For authentication, as of now, we are using a file which stored the email, apikey and site url. This is saved in a file called zuliprc in the /home/user/ directory unencrypted. This is hence vulnerable to masquerading attacks.

The attacker can follow the following steps to gain access to the chatroom:
1. Somehow manage to get the data stored in zuliprc file
2. Create a file in attacker's home/user directory with the name zuliprc and the apikey and email of the victim obtained in Step1
3.  Run zulip-term - now the attacker is logged in with victim's account

Possible fix is to set a device id and also encrypt the file content so that it is more secure.

**Comment by chandansgowda** [comment]
Hey @neiljp 
If this is a valid issue, I would like to work on this with your support.
Thanks

**Comment by thesakshidiggikar** [comment]
Hey, I wanted to participate in this project could you please guide me to whom I can connect to say that I want to participate in "Terminal App: project idea mention .in GSOc project idea.

**Comment by neiljp** [comment]
@thesakshidiggikar I see you've posted in the stream already and got a response, so I'll leave you to investigate on chat.zulip.org and our documentation.

**Comment by neiljp** [comment]
As per discussion in [zulip-terminal](https://chat.zulip.org/#narrow/stream/206-zulip-terminal)>[✔ sensitive data disclosure #T1313](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/.E2.9C.94.20sensitive.20data.20disclosure.20.23T1313), I'm closing this since this is not a significant issue, and if later is determined to be so then it should be fixed at a different level (eg. in the API)
