### ISSUE TITLE
Add feature to read settings from a file before running.

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#18]
Just like vim uses `.vimrc` to store its settings, a setting file for zulip-terminal called `.ztermrc` or similar could be used to read settings like font, theme, etc.

**Comment by mkaito** [comment]
Please also read the `zuliprc` file from a sensible location.

**Comment by amanagr** [comment]
Do mean automatically reading the `zuliprc`  if placed inside the zulip-terminal folder in case no config file is specified?

**Comment by mkaito** [comment]
I just looked at the contents of `zuliprc`. I figure this can be a section in the config file.

You do not want to rely on anything being in the `zulip-terminal` folder, or even being able to write to it. This would make packaging the program extremely hard otherwise.

As for config file placement, look at the [XDG Spec](https://specifications.freedesktop.org/basedir-spec/latest/). Or [this extract](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support), which is probably more readable.

**Comment by timabbott** [comment]
If we want to do something quick here before we have time to do the XDG thing, the default would be to have it look at `~/.zuliprc` with a ` --config` command-line option to specify an alternative path.

**Comment by mkaito** [comment]
You can just check environment for `XDG_CONFIG_DIR`, which can not be set, in which case assume it's `~/.config`. To this value, you append `/zulip/terminal.ini` or something like that. That's all there is to the XDG spec (for this particular use case)

**Comment by KurtovicUM** [comment]
hey, @bolognam and I are exploring the addition of this feature, we'll keep you updated with progress
