### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#225]
Left sidebar:
- [x] could be wider on wider screens. Ideally stream names that fit on web should be fully visible on ZT left sidebar as well
- [x] stream name overflow should indent or I think I would just do: `very very long stream na...`
- [x] I would glue the unread count to the right edge of the sidebar, and make it more visible.
- [x] Blinking cursor is confusing (the fact that you get a blinking cursor) -- urwid doesn't provide option to turn off blinking cursor or hide cursor, could use more deep diving.

- [x] Blue highlight makes the stream name hard to read on some terminal profiles
- [ ] I think it's a bit confusing that hitting "Enter" on a stream name removes the left sidebar

Help menu
- [x] `?` menu: too wide, and the break in `_____    _____` is confusing. I would also reorder this a bit; we can chat separately.
- [ ] This is a big project but I think super high valuable: make the default suggestion context-dependent. 
- [x] I would make the default suggestion highlight `n` and `r` instead of `@`

Message feed:
- [ ] Grey highlight for message in focus is not great; it makes the message too unreadable
- [ ] For replying to a message, I would consider making the top of the compose box something like `zulip-terminal > **feedback**`

**Comment by neiljp** [comment]
@amanagr I think we've only covered the 'glue unread to right edge' task so far?

If you consider the blinking cursor issue fixed, then could you amend the docs to specify that this is expected to be resolved in the terminal app/system end? I think this should still be able to controlled, and is commented to be a missing feature in urwid as per urwid/urwid#170.

**Comment by amanagr** [comment]
Ofcourse, we could do more diving into the blinking cursor part. Also, I think the left sidebar is wide enough.

**Comment by neiljp** [comment]
Blinking cursor & blue highlight contrast should be solved by the recent merge of #281.

**Comment by neiljp** [comment]
"I would make the default suggestion highlight n and r instead of @"! is now tracked in #290, after clarification on #zulip-terminal on chat.zulip.org

**Comment by omi10859** [comment]
> I think it's a bit confusing that hitting "Enter" on a stream name removes the left sidebar 

It is confusing.
Should I make PR to change the behaviour?

**Comment by neiljp** [comment]
> > I think it's a bit confusing that hitting "Enter" on a stream name removes the left sidebar
> 
> It is confusing.
> Should I make PR to change the behaviour?

I *think* we decided this was OK for now, after some conversation at the time. That said, I'm also not sure what the alternative would be, or why it's so confusing - admittedly, talking as an active user of ZT.

If you have ideas on this, I would suggest posting to #zulip-terminal with what you find confusing, and how you think it could be improved. You might search that stream for discussion around that too, since this issue arose originally from feedback from @rishig .

**Comment by omi10859** [comment]
> That said, I'm also not sure what the alternative would be, or why it's so confusing

It was bit confusing in starting as zulip-desktop does not have any such behaviour. 
We can simply fix the left sidebar, same as it is in zulip-desktop or zulip-web

**Comment by neiljp** [comment]
> > That said, I'm also not sure what the alternative would be, or why it's so confusing
> 
> It was bit confusing in starting as zulip-desktop does not have any such behaviour.
> We can simply fix the left sidebar, same as it is in zulip-desktop or zulip-web

Have you explored using the `no_autohide` setting?

**Comment by neiljp** [comment]
Most of these issues, which arose after discussion with @rishig, are now fixed.

The following track the outstanding issues:
* #515 Make help hints context-dependent
* #783 Improve styling of compose-message recipients-area

The grey highlight of messages should have been fixed with either the theme changes or upgrade to urwid 2.1.1, which fixed color rendering in some environments.

Given this, closing this now.
