### ISSUE TITLE
Handle topic links

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#709]
Currently, we don't style or linkify [topic links](https://zulipchat.com/api/get-messages). We could potentially style the topic links as we style other in-line message links and extend the linkifiers.

Note: The concerned endpoint was renamed from `subject_links` to `topic_links` in Zulip 3.0 (feature level 1).

**Comment by Ezio-Sarthak** [comment]
I would like to work on this!
We could also potentially wrap those links into `'ellipsis'` (as provided by urwid) later :)

**Comment by sumanthvrao** [comment]
Cross-linking here to note that zulip/zulip#17124 is now merged. The `topic_links` format would now contain a list of dictionaries rather than the list of URL strings. This means that for ZT to support all server versions, we would have to tweak the way this is handled. Also, the new format benefits from having the text along with the URL for each link in the topic, thus simplifying the client-side parsing logic.
