### ISSUE TITLE
Improve group typeahead

### ISSUE THREAD

**Issue by kaustubh-nair** [zulip/zulip-terminal#732]
With #730 de-prioritizing group typeahead over users, it makes it harder to access group suggestions.
Possible options could be:
1. Use a separate trigger pattern for groups (Maybe something like `@*`?)
2. Handle group matching with users rather than doing it separately, and find some way to mesh together both of the suggestions, rather than just adding both of them.

**Comment by neiljp** [comment]
To clarify my comment on #730, `@*` could be part of the route into implementing autocomplete when the user has already partially typed or completed a name, ie. `@S` might end up with `@**Some User**`, but hand editing the text back to `@**Some` won't then currently autocomplete, and similarly for `@*some group*`. So we could treat those kinds of initial text for users and groups respectively, so that `@**Some` would only autocomplete to users, and `@*S` would only autocomplete to groups.
