### ISSUE TITLE
Narrowing with a contextual message id should select that message

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#954]
If using a link such as generated in a quoted message, then the UI doesn't select that message - which seems like the behavior to be expected.

To reproduce:
* quote a message and send it
* move cursor onto message with quote
* open message info popup, move cursor onto link to original message & press enter

I'd expect the original message to be selected, but we don't do this.

Current behavior is:
* if narrow is loaded/open, do nothing?
* otherwise, load messages around message id; unclear which message is selected?

**Comment by zee-bit** [comment]
@neiljp quoting a message generates a near message url (internal link) to the quoted message, which is already handled by #708?
And, I am not able to reproduce as you said. The UI seems to select the message fine for me.
Could you please clarify once?

**Comment by neiljp** [comment]
At minimum this doesn't occur when within the same narrow.

I thought it also didn't work for some cases when across narrows, but we may need to check manually or maybe check/add tests for this?

**Comment by zee-bit** [comment]
I already did a few manual tests for across narrows, and it seemed to work fine for all cases.

I am not sure if adding tests would be any better since we have most of the tests related to parsing/narrowing already implemented in #708 ?

**Comment by neiljp** [comment]
Have you tried within the same narrow?

**Comment by zee-bit** [comment]
Okay, understood.
So the problem is quoting generates a link to the message in the `['stream', 'topic']` narrow, and if you are already in the same topic narrow, `model.set_narrow()` returns True (it assumes you are already in the correct narrow), and the message doesn't get selected.

Solution - Check if contextual msg-id (`anchor`) is provided to the `controller._narrow_to` method and don't return early in that case. A fix has already been pushed as #967
